### ISSUE TITLE
After installing no secrets.json is generated

### ISSUE THREAD

**Issue by leeish** [podio-export/podio-export#3]
I ran npm install and it installed all the dependencies, but there was nothing else added as per the docs say would happen.

**Comment by marcelobern** [comment]
@leeish seems like the documentation was not clear as the `secrets.json` file should be created by you.

Here is the format of this file:

```json
{
  "CLIENT_ID": "YOUR_CLIENT_ID",
  "CLIENT_SECRET": "YOUR_CLIENT_SECRET",
  "USERNAME": "YOUR_USERNAME",
  "PASSWORD": "YOUR_PASSWORD"
}
```

Please note that you have to provide:
- YOUR_CLIENT_ID & YOUR_CLIENT_SECRET created by going [here](https://podio.com/settings/api).
- YOUR_USERNAME & YOUR_PASSWORD are the username and password for any account which has access to the Podio data you would like to export.

Please let me know if this helps you and in case you run into any additional issues.

**Comment by marcelobern** [comment]
@leeish as I have not hear from you in the last week or so, I am closing this issue.

Please feel free to re-open or open a new one in case you need further assistance.
