### ISSUE TITLE
Cannot run the tool 'npm podio-export'

### ISSUE THREAD

**Issue by DocuZach** [podio-export/podio-export#5]
I am getting as far as installing the npm production packages and creating the sercrets.json file but I am stuck after that. Do I use the command 'npm podio-export' while I am still in the podio-export directory? Is that the correct syntax to run the tool? It just shows me the npm usage page when I run it.

**Comment by marcelobern** [comment]
Happy New Year @DocuZach !

Sorry, the command in the `READMe.md` was incorrect. It is now fixed in PR #6, thanks for reporting this.

The correct command you should run is

`npm run podio-export`
